import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
//Components
import Textos from './components/textos'
import Card1 from './components/Card1'
import Card2 from './components/Card2'
import Card3 from './components/Card3'


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pricing Table</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.center}>
          <Textos/>
        </div>
        <div className={styles.cards}>
          <Card1/>
          <Card2/>
          <Card3/>
        </div>
        

        
      </main>

    </div>
  )
}

export default Home
